export const actionTypes = {
   match: {
      FETCH_MATCHES_REQUEST: 'FETCH_MATCHES_REQUEST',
      FETCH_MATCHES_SUCCESS: 'FETCH_MATCHES_SUCCESS',
      FETCH_MATCHES_ERROR: 'FETCH_MATCHES_ERROR',

      FETCH_CURRENT_GROUP_REQUEST: 'FETCH_CURRENT_GROUP_REQUEST',
      FETCH_CURRENT_GROUP_SUCCESS: 'FETCH_CURRENT_GROUP_SUCCESS1',
      FETCH_CURRENT_GROUP_ERROR: 'FETCH_CURRENT_GROUP_ERROR',
   },
   team: {
      FETCH_TEAMS_REQUEST: 'FETCH_TEAMS_REQUEST',
      FETCH_TEAMS_SUCCESS: 'FETCH_TEAMS_SUCCESS',
      FETCH_TEAMS_ERROR: 'FETCH_TEAMS_ERROR',
      SELECT_TEAM: 'SELECT_TEAM',
   },
};

